services:
  specialisterne weatherapispecialisterneweatherapi:
    image: specialisterne weatherapispecialisterneweatherapi
    build:
      context: .
      dockerfile: Specialisterne WeatherAPI/Dockerfile

