@Specialisterne_WeatherAPI_HostAddress = http://localhost:5014

GET {{Specialisterne_WeatherAPI_HostAddress}}/todos/
Accept: application/json

###

GET {{Specialisterne_WeatherAPI_HostAddress}}/todos/1
Accept: application/json

###
